USE [master]
GO
/****** Object:  Database [Assesment]    Script Date: 2/22/2023 10:32:58 AM ******/
CREATE DATABASE [Assesment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assesment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Assesment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Assesment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Assesment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Assesment] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assesment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Assesment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Assesment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Assesment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Assesment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Assesment] SET ARITHABORT OFF 
GO
ALTER DATABASE [Assesment] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Assesment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Assesment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Assesment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Assesment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Assesment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Assesment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Assesment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Assesment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Assesment] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Assesment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Assesment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Assesment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Assesment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Assesment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Assesment] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Assesment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Assesment] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Assesment] SET  MULTI_USER 
GO
ALTER DATABASE [Assesment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Assesment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Assesment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Assesment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Assesment] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Assesment] SET QUERY_STORE = OFF
GO
USE [Assesment]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Assesment]
GO
/****** Object:  Table [dbo].[Vehicles]    Script Date: 2/22/2023 10:32:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vehicles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Plate] [nchar](10) NOT NULL,
	[Nickname] [nchar](25) NOT NULL,
	[Brand] [nvarchar](25) NOT NULL,
	[ModelYear] [int] NOT NULL,
	[Type] [int] NOT NULL,
	[Color] [nvarchar](20) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Vehicles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Assesment] SET  READ_WRITE 
GO

USE [Assesment]
GO
SET IDENTITY_INSERT [dbo].[Vehicles] ON 
GO
INSERT [dbo].[Vehicles] ([Id], [Plate], [Nickname], [Brand], [ModelYear], [Type], [Color], [IsActive]) VALUES (1, N'35 AU 785 ', N'Karsiyaka Vehicle        ', N'Nissan', 2015, 1, N'Gray', 1)
GO
INSERT [dbo].[Vehicles] ([Id], [Plate], [Nickname], [Brand], [ModelYear], [Type], [Color], [IsActive]) VALUES (2, N'35 KLM 523', N'Ucyol Vehicle            ', N'Opel', 2005, 2, N'White', 1)
GO
SET IDENTITY_INSERT [dbo].[Vehicles] OFF
GO

